import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { SessionProvider } from "next-auth/react";
import Navbar from "./_components/Navbar";
import { siteConfig } from "@/config/site";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: siteConfig.name,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/book.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProvider>
      {" "}
      <html lang="en" className={`${geist.variable}`}>
        <head>
          <script
            data-goatcounter="https://01042020.goatcounter.com/count"
            async
            src="//gc.zgo.at/count.js"
          ></script>
        </head>
        <body>
          <Navbar></Navbar>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Footer></Footer>
        </body>
      </html>
    </SessionProvider>
  );
}
